svm_optimized = fitcsvm(X_train, Y_train, ...
    'KernelFunction', 'rbf', ...
    'OptimizeHyperparameters', 'auto', ...
    'HyperparameterOptimizationOptions', struct('Verbose', 1));

Y_pred_optimized = predict(svm_optimized, X_test);
accuracy_optimized = mean(Y_pred_optimized == Y_test);
fprintf('Accuracy with Optimized Gaussian Kernel: %.2f%%\n', accuracy_optimized * 100);
